CREATE TABLE IF NOT EXISTS `Player` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Club`	TEXT,
	`Height`	INTEGER NOT NULL,
	`Weight`	INTEGER NOT NULL,
	`Position`	INTEGER NOT NULL,
	`PlayerRole`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `ManagerProfile` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Created`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `DatabaseMigrationScript` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`FileName`	TEXT NOT NULL,
	`MigrationDate`	TEXT NOT NULL
);
