CREATE TABLE IF NOT EXISTS `Club` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`HomeColor`	TEXT NOT NULL,
	`AwayColor`	TEXT NOT NULL,
	`ThirdColor`	TEXT NOT NULL
);
INSERT INTO `Club` VALUES (1,'Free Agent', '#FFFFFF', '#FFFFFF', '#FFFFFF');